# Form implementation generated from reading ui file 'whatsapp-messenger-ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #181C14;\n"
"}\n"
"QTabWidget::pane {\n"
"    border: 1px solid #D1D1D1;\n"
"    background-color: #3C3D37;\n"
"    border-radius: 8px;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #DCDCDC;\n"
"    color: #666666;\n"
"    padding: 8px 16px;\n"
"    margin-right: 4px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: white;\n"
"    color: #075E54;\n"
"    font-weight: bold;\n"
"}\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #ECECEC;\n"
"}\n"
"QGroupBox {\n"
"    background-color: #697565;\n"
"    border-radius: 6px;\n"
"    margin-top: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #E0E0E0;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px 0 5px;\n"
"    color: #ECDFCC;\n"
"}\n"
"QTextEdit, QListWidget {\n"
"    border: 1px solid #E0E0E0;\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"    padding: 4px;\n"
"}\n"
"QProgressBar {\n"
"    border: 1px solid #E0E0E0;\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"    text-align: center;\n"
"    color: black;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #25D366;\n"
"    border-radius: 4px;\n"
"}\n"
"QLabel {\n"
"    color: #333333;\n"
"    \n"
"}\n"
"QSpinBox {\n"
"    border: 1px solid #E0E0E0;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"\n"
"#recipientsTab QPushButton, #mediaTab QPushButton{\n"
"border:none;\n"
"padding: 6px;\n"
"border-radius:5px;\n"
"color:white;\n"
"\n"
"}\n"
"#addNumberBtn, #addMediaBtn{\n"
"    background-color: rgb(0, 170, 0); \n"
"}\n"
"#addNumberBtn:hover, #addMediaBtn:hover{\n"
"background-color: rgb(0, 120, 0); \n"
"}\n"
"\n"
"#removeNumberBtn, #removeMediaBtn {\n"
"    background-color:rgb(200, 0, 0) \n"
"}\n"
"#removeNumberBtn:hover,  #removeMediaBtn:hover{\n"
"background-color: rgb(170, 0, 0); \n"
"}\n"
"\n"
"#importNumbersBtn, #clearMediaBtn{\n"
"    background-color: rgb(167, 167, 167); \n"
"}\n"
"#importNumbersBtn:hover, #clearMediaBtn:hover{\n"
"background-color:rgb(191, 222, 194); \n"
"}\n"
"#startBtn {\n"
"    background-color: rgb(0, 170, 0); \n"
"    color:white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"\n"
"}\n"
"#startBtn:hover {\n"
"    background-color: rgb(0, 120, 0); \n"
"\n"
"}\n"
"\n"
"#stopBtn {\n"
"    background-color:rgba(200, 0, 0, 150); \n"
"    color:white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"#stopBtn:hover {\n"
"    background-color: rgb(180, 0, 0);\n"
"     \n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.logoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.logoLabel.setMinimumSize(QtCore.QSize(40, 40))
        self.logoLabel.setMaximumSize(QtCore.QSize(40, 40))
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.headerLayout.addWidget(self.logoLabel)
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setStyleSheet("font-size: 18px; font-weight: bold; color: #075E54;")
        self.titleLabel.setObjectName("titleLabel")
        self.headerLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.headerLayout)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar { alignment: center; }")
        self.tabWidget.setObjectName("tabWidget")
        self.messageTab = QtWidgets.QWidget()
        self.messageTab.setObjectName("messageTab")
        self.messageLayout = QtWidgets.QVBoxLayout(self.messageTab)
        self.messageLayout.setContentsMargins(20, 20, 20, 20)
        self.messageLayout.setSpacing(15)
        self.messageLayout.setObjectName("messageLayout")
        self.messageGroup = QtWidgets.QGroupBox(parent=self.messageTab)
        self.messageGroup.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.messageGroup.setFlat(False)
        self.messageGroup.setCheckable(False)
        self.messageGroup.setObjectName("messageGroup")
        self.messageFormLayout = QtWidgets.QVBoxLayout(self.messageGroup)
        self.messageFormLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.messageFormLayout.setContentsMargins(15, 20, 15, 15)
        self.messageFormLayout.setSpacing(10)
        self.messageFormLayout.setObjectName("messageFormLayout")
        self.messageLabel = QtWidgets.QLabel(parent=self.messageGroup)
        self.messageLabel.setStyleSheet("font-weight: bold; color:#333333;")
        self.messageLabel.setObjectName("messageLabel")
        self.messageFormLayout.addWidget(self.messageLabel)
        self.messageEdit = QtWidgets.QTextEdit(parent=self.messageGroup)
        self.messageEdit.setMinimumSize(QtCore.QSize(0, 120))
        self.messageEdit.setObjectName("messageEdit")
        self.messageFormLayout.addWidget(self.messageEdit)
        self.messageLayout.addWidget(self.messageGroup)
        self.optionsGroup = QtWidgets.QGroupBox(parent=self.messageTab)
        self.optionsGroup.setObjectName("optionsGroup")
        self.optionsFormLayout = QtWidgets.QFormLayout(self.optionsGroup)
        self.optionsFormLayout.setContentsMargins(15, 20, 15, 15)
        self.optionsFormLayout.setSpacing(10)
        self.optionsFormLayout.setObjectName("optionsFormLayout")
        self.delayLabel = QtWidgets.QLabel(parent=self.optionsGroup)
        self.delayLabel.setObjectName("delayLabel")
        self.optionsFormLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.delayLabel)
        self.delayLayout = QtWidgets.QHBoxLayout()
        self.delayLayout.setObjectName("delayLayout")
        self.delaySpin = QtWidgets.QSpinBox(parent=self.optionsGroup)
        self.delaySpin.setMinimumSize(QtCore.QSize(100, 0))
        self.delaySpin.setMinimum(1)
        self.delaySpin.setMaximum(60)
        self.delaySpin.setProperty("value", 3)
        self.delaySpin.setDisplayIntegerBase(10)
        self.delaySpin.setObjectName("delaySpin")
        self.delayLayout.addWidget(self.delaySpin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.delayLayout.addItem(spacerItem1)
        self.optionsFormLayout.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.delayLayout)
        self.messageLayout.addWidget(self.optionsGroup)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.messageLayout.addItem(spacerItem2)
        self.tabWidget.addTab(self.messageTab, "")
        self.recipientsTab = QtWidgets.QWidget()
        self.recipientsTab.setObjectName("recipientsTab")
        self.recipientsLayout = QtWidgets.QVBoxLayout(self.recipientsTab)
        self.recipientsLayout.setContentsMargins(20, 20, 20, 20)
        self.recipientsLayout.setSpacing(15)
        self.recipientsLayout.setObjectName("recipientsLayout")
        self.numbersGroup = QtWidgets.QGroupBox(parent=self.recipientsTab)
        self.numbersGroup.setObjectName("numbersGroup")
        self.numbersLayout = QtWidgets.QVBoxLayout(self.numbersGroup)
        self.numbersLayout.setContentsMargins(15, 20, 15, 15)
        self.numbersLayout.setSpacing(10)
        self.numbersLayout.setObjectName("numbersLayout")
        self.infoLabel = QtWidgets.QLabel(parent=self.numbersGroup)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.infoLabel.setFont(font)
        self.infoLabel.setStyleSheet("font-weight: bold; color:#333333;")
        self.infoLabel.setObjectName("infoLabel")
        self.numbersLayout.addWidget(self.infoLabel)
        self.numbersList = QtWidgets.QListWidget(parent=self.numbersGroup)
        self.numbersList.setStyleSheet("QListWidget::item { padding: 6px; }\n"
"QListWidget::item:alternate { background-color: #F7F7F7; }")
        self.numbersList.setAlternatingRowColors(True)
        self.numbersList.setObjectName("numbersList")
        self.numbersLayout.addWidget(self.numbersList)
        self.numbersButtonsLayout = QtWidgets.QHBoxLayout()
        self.numbersButtonsLayout.setSpacing(10)
        self.numbersButtonsLayout.setObjectName("numbersButtonsLayout")
        self.addNumberBtn = QtWidgets.QPushButton(parent=self.numbersGroup)
        self.addNumberBtn.setStyleSheet("")
        self.addNumberBtn.setObjectName("addNumberBtn")
        self.numbersButtonsLayout.addWidget(self.addNumberBtn)
        self.removeNumberBtn = QtWidgets.QPushButton(parent=self.numbersGroup)
        self.removeNumberBtn.setObjectName("removeNumberBtn")
        self.numbersButtonsLayout.addWidget(self.removeNumberBtn)
        self.importNumbersBtn = QtWidgets.QPushButton(parent=self.numbersGroup)
        self.importNumbersBtn.setObjectName("importNumbersBtn")
        self.numbersButtonsLayout.addWidget(self.importNumbersBtn)
        self.numbersLayout.addLayout(self.numbersButtonsLayout)
        self.recipientsLayout.addWidget(self.numbersGroup)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.recipientsLayout.addItem(spacerItem3)
        self.tabWidget.addTab(self.recipientsTab, "")
        self.mediaTab = QtWidgets.QWidget()
        self.mediaTab.setObjectName("mediaTab")
        self.mediaLayout = QtWidgets.QVBoxLayout(self.mediaTab)
        self.mediaLayout.setContentsMargins(20, 20, 20, 20)
        self.mediaLayout.setSpacing(15)
        self.mediaLayout.setObjectName("mediaLayout")
        self.mediaGroup = QtWidgets.QGroupBox(parent=self.mediaTab)
        self.mediaGroup.setObjectName("mediaGroup")
        self.mediaBoxLayout = QtWidgets.QVBoxLayout(self.mediaGroup)
        self.mediaBoxLayout.setContentsMargins(15, 20, 15, 15)
        self.mediaBoxLayout.setSpacing(10)
        self.mediaBoxLayout.setObjectName("mediaBoxLayout")
        self.mediaInfoLabel = QtWidgets.QLabel(parent=self.mediaGroup)
        self.mediaInfoLabel.setStyleSheet("font-weight: bold; color:#333333;")
        self.mediaInfoLabel.setObjectName("mediaInfoLabel")
        self.mediaBoxLayout.addWidget(self.mediaInfoLabel)
        self.mediaList = QtWidgets.QListWidget(parent=self.mediaGroup)
        self.mediaList.setStyleSheet("QListWidget::item { padding: 6px; }\n"
"QListWidget::item:alternate { background-color: #F7F7F7; }")
        self.mediaList.setAlternatingRowColors(True)
        self.mediaList.setObjectName("mediaList")
        self.mediaBoxLayout.addWidget(self.mediaList)
        self.mediaButtonsLayout = QtWidgets.QHBoxLayout()
        self.mediaButtonsLayout.setSpacing(10)
        self.mediaButtonsLayout.setObjectName("mediaButtonsLayout")
        self.addMediaBtn = QtWidgets.QPushButton(parent=self.mediaGroup)
        self.addMediaBtn.setObjectName("addMediaBtn")
        self.mediaButtonsLayout.addWidget(self.addMediaBtn)
        self.removeMediaBtn = QtWidgets.QPushButton(parent=self.mediaGroup)
        self.removeMediaBtn.setObjectName("removeMediaBtn")
        self.mediaButtonsLayout.addWidget(self.removeMediaBtn)
        self.clearMediaBtn = QtWidgets.QPushButton(parent=self.mediaGroup)
        self.clearMediaBtn.setObjectName("clearMediaBtn")
        self.mediaButtonsLayout.addWidget(self.clearMediaBtn)
        self.mediaBoxLayout.addLayout(self.mediaButtonsLayout)
        self.mediaLayout.addWidget(self.mediaGroup)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mediaLayout.addItem(spacerItem4)
        self.tabWidget.addTab(self.mediaTab, "")
        self.statusTab = QtWidgets.QWidget()
        self.statusTab.setObjectName("statusTab")
        self.statusLayout = QtWidgets.QVBoxLayout(self.statusTab)
        self.statusLayout.setContentsMargins(20, 20, 20, 20)
        self.statusLayout.setSpacing(15)
        self.statusLayout.setObjectName("statusLayout")
        self.statusGroup = QtWidgets.QGroupBox(parent=self.statusTab)
        self.statusGroup.setObjectName("statusGroup")
        self.statusFormLayout = QtWidgets.QVBoxLayout(self.statusGroup)
        self.statusFormLayout.setContentsMargins(15, 20, 15, 15)
        self.statusFormLayout.setSpacing(10)
        self.statusFormLayout.setObjectName("statusFormLayout")
        self.statusText = QtWidgets.QTextEdit(parent=self.statusGroup)
        self.statusText.setStyleSheet("QTextEdit {\n"
        "    background-color: #F7F7F7;\n"
        "    font-family: \'Consolas\', \'Courier New\', monospace;\n"
        "    line-height: 1.4;\n"
        "    color:black;\n   "
        "}")
        self.statusText.setReadOnly(True)
        self.statusText.setObjectName("statusText")
        self.statusFormLayout.addWidget(self.statusText)
        self.progressLabel = QtWidgets.QLabel(parent=self.statusGroup)
        self.progressLabel.setStyleSheet("font-weight: bold;")
        self.progressLabel.setObjectName("progressLabel")
        self.statusFormLayout.addWidget(self.progressLabel)
        self.progressBar = QtWidgets.QProgressBar(parent=self.statusGroup)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.statusFormLayout.addWidget(self.progressBar)
        self.statusButtonsLayout = QtWidgets.QHBoxLayout()
        self.statusButtonsLayout.setSpacing(10)
        self.statusButtonsLayout.setObjectName("statusButtonsLayout")
        self.startBtn = QtWidgets.QPushButton(parent=self.statusGroup)
        self.startBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.startBtn.setObjectName("startBtn")
        self.statusButtonsLayout.addWidget(self.startBtn)
        self.stopBtn = QtWidgets.QPushButton(parent=self.statusGroup)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.stopBtn.setObjectName("stopBtn")
        self.statusButtonsLayout.addWidget(self.stopBtn)
        self.statusFormLayout.addLayout(self.statusButtonsLayout)
        self.statusLayout.addWidget(self.statusGroup)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.statusLayout.addItem(spacerItem5)
        self.tabWidget.addTab(self.statusTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.footerLayout = QtWidgets.QHBoxLayout()
        self.footerLayout.setObjectName("footerLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem6)
        self.footerLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.footerLabel.setStyleSheet("color: #666666; font-size: 10px;")
        self.footerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.footerLabel.setObjectName("footerLabel")
        self.footerLayout.addWidget(self.footerLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.footerLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WhatsApp Toplu Mesaj"))
        self.titleLabel.setText(_translate("MainWindow", "WhatsApp Toplu Mesaj Gönderme"))
        self.messageGroup.setTitle(_translate("MainWindow", "Mesaj İçeriği"))
        self.messageLabel.setText(_translate("MainWindow", "Gönderilecek Mesaj:"))
        self.messageEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.messageEdit.setPlaceholderText(_translate("MainWindow", "Buraya gönderilecek mesajı yazın..."))
        self.optionsGroup.setTitle(_translate("MainWindow", "Gönderim Seçenekleri"))
        self.delayLabel.setText(_translate("MainWindow", "Mesajlar Arası Bekleme Süresi:"))
        self.delaySpin.setSuffix(_translate("MainWindow", " saniye"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.messageTab), _translate("MainWindow", "Mesaj Ayarları"))
        self.numbersGroup.setTitle(_translate("MainWindow", "Telefon Numaraları"))
        self.infoLabel.setText(_translate("MainWindow", "Telefon numaralarını ülke koduyla birlikte ekleyin (örn: 905551234567)"))
        self.addNumberBtn.setText(_translate("MainWindow", "Numara Ekle"))
        self.removeNumberBtn.setText(_translate("MainWindow", "Seçili Numarayı Sil"))
        self.importNumbersBtn.setText(_translate("MainWindow", "Numaraları İçe Aktar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recipientsTab), _translate("MainWindow", "Alıcılar"))
        self.mediaGroup.setTitle(_translate("MainWindow", "Eklenecek Medya Dosyaları"))
        self.mediaInfoLabel.setText(_translate("MainWindow", "Göndermek istediğiniz resim, video veya diğer dosyaları ekleyin"))
        self.addMediaBtn.setText(_translate("MainWindow", "Dosya Ekle"))
        self.removeMediaBtn.setText(_translate("MainWindow", "Seçili Dosyayı Kaldır"))
        self.clearMediaBtn.setText(_translate("MainWindow", "Tüm Dosyaları Temizle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mediaTab), _translate("MainWindow", "Medya Dosyaları"))
        self.statusGroup.setTitle(_translate("MainWindow", "İşlem Durumu"))
        self.progressLabel.setText(_translate("MainWindow", "İlerleme:"))
        self.startBtn.setText(_translate("MainWindow", "Gönderimi Başlat"))
        self.stopBtn.setText(_translate("MainWindow", "Gönderimi Durdur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statusTab), _translate("MainWindow", "Durum"))
        self.footerLabel.setText(_translate("MainWindow", "WhatsApp Toplu Mesaj Gönderme Uygulaması © 2025"))
